import Head from 'next/head'
import  Footer  from '../components/Footer';
import Languages from '../components/Languages';
import { initializeApollo } from '../lib/apolloClient';
import { CONTINENT_QUERY } from '../lib/queries';
import styles from '../styles/Home.module.css'

export default function Continent({continent}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Continent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h3>Countries of {continent.name} (SSR) </h3>
      <ul className={styles.countries}>
        {
          continent && continent.countries.map((country) => {
            return (<li key={country.code}>{country.name}</li>)
          })
        }
      </ul>
     

      </main>

      <Footer  />
    </div>
  )
}


export async function getServerSideProps(context) {
    
    const { code } = context.query;

    const apolloClient = initializeApollo();

    const { data : {continent} } = await apolloClient.query({
      query: CONTINENT_QUERY,
      variables: {
        continentCode : code.toUpperCase()
      }
    });

 
    return { props: { continent} };

}